-- File: schema.sql
-- Description: Complete production schema initialization script for multi-tenant widget platform

-- Drop existing tables in reverse dependency order to ensure a clean, reproducible state
DROP TABLE IF EXISTS submissions CASCADE;
DROP TABLE IF EXISTS widgets CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;

-- Create tenants table to store client organization credentials and administrative profiles
CREATE TABLE tenants (
  id SERIAL PRIMARY KEY,                                       -- Auto-incrementing primary key identifier for each tenant
  email VARCHAR(255) UNIQUE NOT NULL,                          -- Unique administrative email address used for login
  password_hash VARCHAR(255) NOT NULL,                         -- Salted password hash generated by bcrypt/argon2
  company_name VARCHAR(255) NOT NULL,                          -- Registered legal or display organization name
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP -- Audit timestamp recording exact account creation in UTC
);

-- Create widgets table storing embeddable UI configurations and options
CREATE TABLE widgets (
  id SERIAL PRIMARY KEY,                                       -- Auto-incrementing primary key identifier for each widget
  tenant_id INT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, -- Foreign key binding widget to parent tenant owner
  name VARCHAR(255) NOT NULL,                                  -- Friendly display title identifying the widget in dashboard
  type VARCHAR(100) NOT NULL,                                  -- Functional classification key (e.g., 'lead_capture', 'feedback')
  config JSONB DEFAULT '{}'::jsonb,                            -- Native JSONB document storing dynamic layout/form parameters
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP -- Audit timestamp recording exact widget creation in UTC
);

-- Create submissions table to persist end-user web form data from external websites
CREATE TABLE submissions (
  id SERIAL PRIMARY KEY,                                       -- Auto-incrementing primary key identifier for each submission
  widget_id INT NOT NULL REFERENCES widgets(id) ON DELETE CASCADE, -- Foreign key binding submission directly to parent widget
  payload JSONB NOT NULL,                                      -- Native JSONB document capturing arbitrary form field key-value pairs
  metadata JSONB DEFAULT '{}'::jsonb,                          -- JSONB document storing client browser metadata (e.g., IP, page_url)
  geo JSONB,                                                   -- Location looked up from the visitor's IP (country, city, provider); NULL when no provider could answer
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP -- Audit timestamp recording exact submission receipt in UTC
);

-- Seed default test tenant record for local development and test environment execution
INSERT INTO tenants (id, email, password_hash, company_name)
VALUES (1, 'dev@flyrank.ai', '$2b$10$e83...mockhash', 'FlyRank Test Org')
ON CONFLICT (id) DO NOTHING;                                  -- Prevent execution errors on repeated schema seeding runs

-- Seed default test widget record (ID = 1) required for Stage 4 verification tests
INSERT INTO widgets (id, tenant_id, name, type, config)
VALUES (1, 1, 'Stage 4 Public Form Widget', 'lead_capture', '{"fields": ["email", "feedback"]}'::jsonb)
ON CONFLICT (id) DO NOTHING;                                  -- Prevent execution errors on repeated schema seeding runs

-- FIX: the seed rows above insert explicit ids (1), which does NOT advance the SERIAL counters.
-- Without this, the next INSERT that relies on the default id (e.g. POST /api/widgets or setup_db.js)
-- would try to use id = 1 again and fail with 'duplicate key value violates unique constraint'.
SELECT setval(pg_get_serial_sequence('tenants', 'id'), (SELECT COALESCE(MAX(id), 1) FROM tenants)); -- Move tenants id counter past the seeded row
SELECT setval(pg_get_serial_sequence('widgets', 'id'), (SELECT COALESCE(MAX(id), 1) FROM widgets)); -- Move widgets id counter past the seeded row

-- Create B-Tree index on widgets.tenant_id to optimize tenant-isolated dashboard queries
CREATE INDEX idx_widgets_tenant_id ON widgets(tenant_id);

-- FIX (Stage 6): composite index on (widget_id, created_at DESC). It serves "all submissions of a widget" (widget_id alone, as before)
-- AND the dashboard's newest-first lists and time-window filters, so the old single-column index on widget_id is no longer needed.
CREATE INDEX idx_submissions_widget_created ON submissions(widget_id, created_at DESC);

-- Create GIN (Generalized Inverted Index) on submissions.payload to enable fast JSON key-value searches
CREATE INDEX idx_submissions_payload_gin ON submissions USING GIN (payload);